name: "Increase Swap"
version: "1.0.2"
slug: increase_swap_addon
description: "This add-on increases the swap space on your system."
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
  - i386
startup: services
boot: "auto"
init: false
options:
  swap_size: 32
schema:
  swap_size: int(16,32)
privileged:
  - SYS_ADMIN
